-- ==============================================================================
-- TripNest — Production PostgreSQL Schema (schema-postgres.sql)
-- Target: PostgreSQL 14+ / Azure Database for PostgreSQL Flexible Server
-- Fully compatible with Hibernate 6 / Spring Boot 3 ddl-auto=validate
-- ==============================================================================

-- Drop tables in reverse foreign-key dependency order
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS settlements CASCADE;
DROP TABLE IF EXISTS expense_splits CASCADE;
DROP TABLE IF EXISTS group_members CASCADE;
DROP TABLE IF EXISTS group_messages CASCADE;
DROP TABLE IF EXISTS group_memberships CASCADE;
DROP TABLE IF EXISTS travel_groups CASCADE;
DROP TABLE IF EXISTS activities CASCADE;
DROP TABLE IF EXISTS itineraries CASCADE;
DROP TABLE IF EXISTS budgets CASCADE;
DROP TABLE IF EXISTS expenses CASCADE;
DROP TABLE IF EXISTS favorite_destinations CASCADE;
DROP TABLE IF EXISTS travel_documents CASCADE;
DROP TABLE IF EXISTS travel_memory_images CASCADE;
DROP TABLE IF EXISTS travel_memories CASCADE;
DROP TABLE IF EXISTS destinations CASCADE;
DROP TABLE IF EXISTS notification_preferences CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS password_reset_tokens CASCADE;
DROP TABLE IF EXISTS preference_trip_types CASCADE;
DROP TABLE IF EXISTS travel_preferences CASCADE;
DROP TABLE IF EXISTS trip_shares CASCADE;
DROP TABLE IF EXISTS trips CASCADE;
DROP TABLE IF EXISTS contact_messages CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ------------------------------------------------------------------------------
-- 1. Roles
-- ------------------------------------------------------------------------------
CREATE TABLE roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(20) DEFAULT NULL
);

-- ------------------------------------------------------------------------------
-- 2. Users (profile_picture_url removed in B2 hardening)
-- ------------------------------------------------------------------------------
CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) NOT NULL,
  email varchar(100) NOT NULL,
  password varchar(120) NOT NULL,
  first_name varchar(50) DEFAULT NULL,
  last_name varchar(50) DEFAULT NULL,
  phone varchar(15) DEFAULT NULL,
  bio varchar(300) DEFAULT NULL,
  country varchar(100) DEFAULT NULL,
  state varchar(100) DEFAULT NULL,
  city varchar(100) DEFAULT NULL,
  date_of_birth date DEFAULT NULL,
  gender varchar(20) DEFAULT NULL,
  occupation varchar(100) DEFAULT NULL,
  email_verified boolean NOT NULL DEFAULT FALSE,
  travel_style varchar(50) DEFAULT NULL,
  preferred_transport varchar(50) DEFAULT NULL,
  accommodation_preference varchar(50) DEFAULT NULL,
  dream_destination varchar(100) DEFAULT NULL,
  favorite_destination varchar(100) DEFAULT NULL,
  passport_holder boolean NOT NULL DEFAULT FALSE,
  emergency_contact_name varchar(100) DEFAULT NULL,
  emergency_contact_relationship varchar(50) DEFAULT NULL,
  emergency_contact_phone varchar(15) DEFAULT NULL,
  github varchar(500) DEFAULT NULL,
  linkedin varchar(500) DEFAULT NULL,
  instagram varchar(500) DEFAULT NULL,
  portfolio varchar(500) DEFAULT NULL,
  enabled boolean NOT NULL DEFAULT TRUE,
  password_change_required boolean NOT NULL DEFAULT FALSE,
  temporary_password_expiry timestamp(6) DEFAULT NULL,
  provider varchar(20) DEFAULT 'LOCAL',
  created_at timestamp(6) DEFAULT NULL,
  CONSTRAINT uk_users_username UNIQUE (username),
  CONSTRAINT uk_users_email UNIQUE (email)
);

-- ------------------------------------------------------------------------------
-- 3. User Roles (Join Table)
-- ------------------------------------------------------------------------------
CREATE TABLE user_roles (
  user_id bigint NOT NULL,
  role_id bigint NOT NULL,
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id)
);
CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);

-- ------------------------------------------------------------------------------
-- 4. Destinations
-- ------------------------------------------------------------------------------
CREATE TABLE destinations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  state varchar(100) DEFAULT NULL,
  country varchar(100) DEFAULT NULL,
  description varchar(1000) DEFAULT NULL,
  category varchar(100) DEFAULT NULL,
  image_url varchar(500) DEFAULT NULL,
  best_season varchar(100) DEFAULT NULL,
  estimated_budget double precision DEFAULT NULL,
  recommended_days integer DEFAULT NULL,
  latitude double precision DEFAULT NULL,
  longitude double precision DEFAULT NULL,
  rating double precision DEFAULT NULL,
  popular boolean NOT NULL DEFAULT FALSE,
  average_cost double precision DEFAULT NULL,
  best_time_to_visit varchar(200) DEFAULT NULL,
  city varchar(100) DEFAULT NULL,
  climate varchar(100) DEFAULT NULL,
  CONSTRAINT uk_destination_name_state_country UNIQUE (name, state, country)
);

-- ------------------------------------------------------------------------------
-- 5. Trips
-- ------------------------------------------------------------------------------
CREATE TABLE trips (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(100) NOT NULL,
  description varchar(500) DEFAULT NULL,
  destination varchar(100) NOT NULL,
  start_date date DEFAULT NULL,
  end_date date DEFAULT NULL,
  number_of_travelers integer DEFAULT NULL,
  budget double precision DEFAULT NULL,
  status varchar(50) DEFAULT 'PLANNING',
  reminder_sent boolean DEFAULT FALSE,
  reminder7day_sent boolean DEFAULT FALSE,
  reminder3day_sent boolean DEFAULT FALSE,
  reminder24hour_sent boolean DEFAULT FALSE,
  trip_started_sent boolean DEFAULT FALSE,
  trip_completed_sent boolean DEFAULT FALSE,
  user_id bigint DEFAULT NULL,
  created_at timestamp(6) DEFAULT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  CONSTRAINT fk_trips_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_trips_user_id ON trips (user_id);

-- ------------------------------------------------------------------------------
-- 6. Budgets
-- ------------------------------------------------------------------------------
CREATE TABLE budgets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  total_amount double precision DEFAULT NULL,
  spent_amount double precision DEFAULT 0.0,
  remaining_amount double precision DEFAULT NULL,
  currency varchar(100) DEFAULT 'INR',
  alert80sent boolean DEFAULT FALSE,
  alert100sent boolean DEFAULT FALSE,
  trip_id bigint DEFAULT NULL,
  created_at timestamp(6) DEFAULT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  CONSTRAINT uk_budgets_trip_id UNIQUE (trip_id),
  CONSTRAINT fk_budgets_trip FOREIGN KEY (trip_id) REFERENCES trips (id)
);

-- ------------------------------------------------------------------------------
-- 7. Expenses
-- ------------------------------------------------------------------------------
CREATE TABLE expenses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(100) DEFAULT NULL,
  amount double precision DEFAULT NULL,
  category varchar(50) DEFAULT NULL,
  description varchar(500) DEFAULT NULL,
  date date DEFAULT NULL,
  receipt_url varchar(200) DEFAULT NULL,
  trip_id bigint DEFAULT NULL,
  user_id bigint DEFAULT NULL,
  created_at timestamp(6) DEFAULT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  CONSTRAINT fk_expenses_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
  CONSTRAINT fk_expenses_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_expenses_trip_id ON expenses (trip_id);
CREATE INDEX idx_expenses_user_id ON expenses (user_id);

-- ------------------------------------------------------------------------------
-- 7a. Expense Splits
-- ------------------------------------------------------------------------------
CREATE TABLE expense_splits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount numeric(10,2) NOT NULL,
  is_settled boolean NOT NULL DEFAULT FALSE,
  settled_at timestamp(6) DEFAULT NULL,
  expense_id bigint NOT NULL,
  user_id bigint NOT NULL,
  CONSTRAINT fk_expense_splits_expense FOREIGN KEY (expense_id) REFERENCES expenses (id) ON DELETE CASCADE,
  CONSTRAINT fk_expense_splits_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_expense_splits_expense_id ON expense_splits (expense_id);
CREATE INDEX idx_expense_splits_user_id ON expense_splits (user_id);

-- ------------------------------------------------------------------------------
-- 7b. Settlements
-- ------------------------------------------------------------------------------
CREATE TABLE settlements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount numeric(10,2) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'PENDING',
  created_at timestamp(6) DEFAULT NULL,
  settled_at timestamp(6) DEFAULT NULL,
  payee_id bigint NOT NULL,
  payer_id bigint NOT NULL,
  trip_id bigint NOT NULL,
  CONSTRAINT fk_settlements_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
  CONSTRAINT fk_settlements_payer FOREIGN KEY (payer_id) REFERENCES users (id),
  CONSTRAINT fk_settlements_payee FOREIGN KEY (payee_id) REFERENCES users (id)
);
CREATE INDEX idx_settlements_trip_id ON settlements (trip_id);
CREATE INDEX idx_settlements_payer_id ON settlements (payer_id);
CREATE INDEX idx_settlements_payee_id ON settlements (payee_id);

-- ------------------------------------------------------------------------------
-- 8. Itineraries
-- ------------------------------------------------------------------------------
CREATE TABLE itineraries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date date DEFAULT NULL,
  notes varchar(500) DEFAULT NULL,
  trip_id bigint DEFAULT NULL,
  user_id bigint DEFAULT NULL,
  created_at timestamp(6) DEFAULT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  CONSTRAINT fk_itineraries_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
  CONSTRAINT fk_itineraries_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_itineraries_trip_id ON itineraries (trip_id);
CREATE INDEX idx_itineraries_user_id ON itineraries (user_id);

-- ------------------------------------------------------------------------------
-- 9. Activities
-- ------------------------------------------------------------------------------
CREATE TABLE activities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(100) DEFAULT NULL,
  description varchar(500) DEFAULT NULL,
  start_time time(6) DEFAULT NULL,
  end_time time(6) DEFAULT NULL,
  location varchar(200) DEFAULT NULL,
  type varchar(50) DEFAULT NULL,
  cost double precision DEFAULT NULL,
  linked_expense_id bigint DEFAULT NULL,
  reminder_sent boolean DEFAULT FALSE,
  reminder varchar(50) DEFAULT 'THIRTY_MINUTES',
  itinerary_id bigint DEFAULT NULL,
  user_id bigint DEFAULT NULL,
  created_at timestamp(6) DEFAULT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  CONSTRAINT fk_activities_itinerary FOREIGN KEY (itinerary_id) REFERENCES itineraries (id),
  CONSTRAINT fk_activities_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_activities_itinerary_id ON activities (itinerary_id);
CREATE INDEX idx_activities_user_id ON activities (user_id);

-- ------------------------------------------------------------------------------
-- 10. Favorite Destinations
-- ------------------------------------------------------------------------------
CREATE TABLE favorite_destinations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint DEFAULT NULL,
  destination_id bigint DEFAULT NULL,
  created_at timestamp(6) DEFAULT NULL,
  CONSTRAINT uk_favorite_destinations_user_dest UNIQUE (user_id, destination_id),
  CONSTRAINT fk_favorite_destinations_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_favorite_destinations_destination FOREIGN KEY (destination_id) REFERENCES destinations (id)
);
CREATE INDEX idx_favorite_destinations_dest_id ON favorite_destinations (destination_id);

-- ------------------------------------------------------------------------------
-- 11. Travel Groups
-- ------------------------------------------------------------------------------
CREATE TABLE travel_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) DEFAULT NULL,
  description varchar(500) DEFAULT NULL,
  created_by bigint DEFAULT NULL,
  trip_id bigint DEFAULT NULL,
  created_at timestamp(6) DEFAULT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  CONSTRAINT fk_travel_groups_creator FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_travel_groups_trip FOREIGN KEY (trip_id) REFERENCES trips (id)
);
CREATE INDEX idx_travel_groups_created_by ON travel_groups (created_by);
CREATE INDEX idx_travel_groups_trip_id ON travel_groups (trip_id);

-- ------------------------------------------------------------------------------
-- 12. Group Members (Join Table)
-- ------------------------------------------------------------------------------
CREATE TABLE group_members (
  group_id bigint NOT NULL,
  user_id bigint NOT NULL,
  PRIMARY KEY (group_id, user_id),
  CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES travel_groups (id),
  CONSTRAINT fk_group_members_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_group_members_user_id ON group_members (user_id);

-- ------------------------------------------------------------------------------
-- 13. Group Memberships
-- ------------------------------------------------------------------------------
CREATE TABLE group_memberships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL,
  user_id bigint NOT NULL,
  invited_by_user_id bigint DEFAULT NULL,
  invited_by_id bigint DEFAULT NULL,
  role varchar(20) NOT NULL DEFAULT 'MEMBER',
  status varchar(20) NOT NULL DEFAULT 'PENDING',
  trip_permission varchar(20) DEFAULT 'VIEW',
  invited_at timestamp(6) NOT NULL,
  joined_at timestamp(6) DEFAULT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  CONSTRAINT uk_group_memberships_group_user UNIQUE (group_id, user_id),
  CONSTRAINT fk_group_memberships_group FOREIGN KEY (group_id) REFERENCES travel_groups (id),
  CONSTRAINT fk_group_memberships_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_group_memberships_invited_by FOREIGN KEY (invited_by_user_id) REFERENCES users (id)
);
CREATE INDEX idx_group_memberships_user_id ON group_memberships (user_id);
CREATE INDEX idx_group_memberships_invited_by ON group_memberships (invited_by_user_id);

-- ------------------------------------------------------------------------------
-- 14. Group Messages
-- ------------------------------------------------------------------------------
CREATE TABLE group_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content varchar(1000) NOT NULL,
  group_id bigint NOT NULL,
  user_id bigint NOT NULL,
  created_at timestamp(6) NOT NULL,
  CONSTRAINT fk_group_messages_group FOREIGN KEY (group_id) REFERENCES travel_groups (id),
  CONSTRAINT fk_group_messages_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_group_msg_created ON group_messages (group_id, created_at);
CREATE INDEX idx_group_messages_user_id ON group_messages (user_id);

-- ------------------------------------------------------------------------------
-- 15. Travel Memories
-- ------------------------------------------------------------------------------
CREATE TABLE travel_memories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(150) NOT NULL,
  caption varchar(2000) DEFAULT NULL,
  location_name varchar(200) DEFAULT NULL,
  image_url varchar(500) DEFAULT NULL,
  stored_file_name varchar(255) DEFAULT NULL,
  visibility varchar(20) NOT NULL DEFAULT 'PRIVATE',
  trip_id bigint DEFAULT NULL,
  destination_id bigint DEFAULT NULL,
  user_id bigint NOT NULL,
  created_at timestamp(6) DEFAULT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  CONSTRAINT fk_travel_memories_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_travel_memories_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
  CONSTRAINT fk_travel_memories_destination FOREIGN KEY (destination_id) REFERENCES destinations (id)
);
CREATE INDEX idx_memory_user_id ON travel_memories (user_id);
CREATE INDEX idx_memory_visibility ON travel_memories (visibility);
CREATE INDEX idx_memory_trip_id ON travel_memories (trip_id);
CREATE INDEX idx_memory_dest_id ON travel_memories (destination_id);
CREATE INDEX idx_memory_dest_vis_created ON travel_memories (destination_id, visibility, created_at);

-- ------------------------------------------------------------------------------
-- 16. Travel Memory Images (Multi-Image Support)
-- ------------------------------------------------------------------------------
CREATE TABLE travel_memory_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  memory_id bigint NOT NULL,
  stored_file_name varchar(255) NOT NULL,
  file_url varchar(500) NOT NULL,
  original_file_name varchar(255) DEFAULT NULL,
  content_type varchar(100) DEFAULT NULL,
  file_size bigint DEFAULT NULL,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp(6) DEFAULT NULL,
  CONSTRAINT fk_travel_memory_images_memory FOREIGN KEY (memory_id) REFERENCES travel_memories (id) ON DELETE CASCADE
);
CREATE INDEX idx_mem_img_memory_id ON travel_memory_images (memory_id);
CREATE INDEX idx_mem_img_stored_name ON travel_memory_images (stored_file_name);

-- ------------------------------------------------------------------------------
-- 17. Travel Documents
-- ------------------------------------------------------------------------------
CREATE TABLE travel_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name varchar(255) DEFAULT NULL,
  file_type varchar(100) DEFAULT NULL,
  file_url varchar(500) DEFAULT NULL,
  stored_file_name varchar(255) DEFAULT NULL,
  document_type varchar(50) DEFAULT NULL,
  trip_id bigint DEFAULT NULL,
  user_id bigint DEFAULT NULL,
  created_at timestamp(6) DEFAULT NULL,
  CONSTRAINT uk_travel_documents_stored_file_name UNIQUE (stored_file_name),
  CONSTRAINT fk_travel_documents_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
  CONSTRAINT fk_travel_documents_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_travel_documents_trip_id ON travel_documents (trip_id);
CREATE INDEX idx_travel_documents_user_id ON travel_documents (user_id);

-- ------------------------------------------------------------------------------
-- 18. Trip Shares
-- ------------------------------------------------------------------------------
CREATE TABLE trip_shares (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id bigint DEFAULT NULL,
  shared_with_user_id bigint DEFAULT NULL,
  shared_by_user_id bigint DEFAULT NULL,
  permission varchar(50) DEFAULT 'VIEW',
  status varchar(50) DEFAULT 'PENDING',
  created_at timestamp(6) DEFAULT NULL,
  CONSTRAINT uk_trip_shares_trip_shared_with UNIQUE (trip_id, shared_with_user_id),
  CONSTRAINT fk_trip_shares_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
  CONSTRAINT fk_trip_shares_shared_with FOREIGN KEY (shared_with_user_id) REFERENCES users (id),
  CONSTRAINT fk_trip_shares_shared_by FOREIGN KEY (shared_by_user_id) REFERENCES users (id)
);
CREATE INDEX idx_trip_shares_shared_with ON trip_shares (shared_with_user_id);
CREATE INDEX idx_trip_shares_shared_by ON trip_shares (shared_by_user_id);

-- ------------------------------------------------------------------------------
-- 19. Notifications
-- ------------------------------------------------------------------------------
CREATE TABLE notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(200) DEFAULT NULL,
  message varchar(500) DEFAULT NULL,
  type varchar(50) DEFAULT NULL,
  is_read boolean NOT NULL DEFAULT FALSE,
  user_id bigint DEFAULT NULL,
  reference_id bigint DEFAULT NULL,
  created_at timestamp(6) DEFAULT NULL,
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_notifications_user_id ON notifications (user_id);

-- ------------------------------------------------------------------------------
-- 20. Notification Preferences
-- ------------------------------------------------------------------------------
CREATE TABLE notification_preferences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint DEFAULT NULL,
  trip_reminders boolean NOT NULL DEFAULT TRUE,
  activity_reminders boolean NOT NULL DEFAULT TRUE,
  budget_alerts boolean NOT NULL DEFAULT TRUE,
  group_notifications boolean NOT NULL DEFAULT TRUE,
  trip_share_notifications boolean NOT NULL DEFAULT TRUE,
  created_at timestamp(6) DEFAULT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  CONSTRAINT uk_notification_preferences_user UNIQUE (user_id),
  CONSTRAINT fk_notification_preferences_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ------------------------------------------------------------------------------
-- 21. Travel Preferences
-- ------------------------------------------------------------------------------
CREATE TABLE travel_preferences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint DEFAULT NULL,
  preferred_budget_range varchar(20) DEFAULT NULL,
  preferred_travel_style varchar(20) DEFAULT NULL,
  created_at timestamp(6) DEFAULT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  CONSTRAINT uk_travel_preferences_user UNIQUE (user_id),
  CONSTRAINT fk_travel_preferences_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ------------------------------------------------------------------------------
-- 22. Preference Trip Types (ElementCollection)
-- ------------------------------------------------------------------------------
CREATE TABLE preference_trip_types (
  preference_id bigint NOT NULL,
  trip_type varchar(255) DEFAULT NULL,
  CONSTRAINT fk_preference_trip_types_pref FOREIGN KEY (preference_id) REFERENCES travel_preferences (id)
);
CREATE INDEX idx_pref_trip_types_pref_id ON preference_trip_types (preference_id);

-- ------------------------------------------------------------------------------
-- 23. Password Reset Tokens
-- ------------------------------------------------------------------------------
CREATE TABLE password_reset_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token varchar(255) DEFAULT NULL,
  user_id bigint DEFAULT NULL,
  expiry_date timestamp(6) DEFAULT NULL,
  used boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT uk_password_reset_tokens_token UNIQUE (token),
  CONSTRAINT uk_password_reset_tokens_user UNIQUE (user_id),
  CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ------------------------------------------------------------------------------
-- 24. Contact Messages
-- ------------------------------------------------------------------------------
CREATE TABLE contact_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  email varchar(100) NOT NULL,
  category varchar(30) NOT NULL,
  subject varchar(200) NOT NULL,
  message varchar(3000) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'NEW',
  user_id bigint DEFAULT NULL,
  created_at timestamp(6) NOT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  CONSTRAINT fk_contact_messages_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_contact_status ON contact_messages (status);
CREATE INDEX idx_contact_created_at ON contact_messages (created_at);
CREATE INDEX idx_contact_email ON contact_messages (email);
CREATE INDEX idx_contact_category ON contact_messages (category);
CREATE INDEX idx_contact_user_id ON contact_messages (user_id);

-- ------------------------------------------------------------------------------
-- Seed Initial Roles
-- ------------------------------------------------------------------------------
INSERT INTO roles (name) VALUES ('ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_GROUP_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_TRAVELER') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_USER') ON CONFLICT DO NOTHING;
