-- ==============================================================================
-- TripNest — Feature 7: Expense Splits & Manual Debt Settlement
-- Target: PostgreSQL 14+ / Azure Database for PostgreSQL Flexible Server
-- Fully compatible with Hibernate 6 / Spring Boot 3 ddl-auto=validate
-- ==============================================================================

-- 1. Expense Splits
CREATE TABLE IF NOT EXISTS expense_splits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount numeric(10,2) NOT NULL,
  is_settled boolean NOT NULL DEFAULT FALSE,
  settled_at timestamp(6) DEFAULT NULL,
  expense_id bigint NOT NULL,
  user_id bigint NOT NULL,
  CONSTRAINT fk_expense_splits_expense FOREIGN KEY (expense_id) REFERENCES expenses (id) ON DELETE CASCADE,
  CONSTRAINT fk_expense_splits_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_expense_splits_expense_id ON expense_splits (expense_id);
CREATE INDEX IF NOT EXISTS idx_expense_splits_user_id ON expense_splits (user_id);

-- 2. Settlements
CREATE TABLE IF NOT EXISTS settlements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount numeric(10,2) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'PENDING',
  created_at timestamp(6) DEFAULT NULL,
  settled_at timestamp(6) DEFAULT NULL,
  payee_id bigint NOT NULL,
  payer_id bigint NOT NULL,
  trip_id bigint NOT NULL,
  CONSTRAINT fk_settlements_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
  CONSTRAINT fk_settlements_payer FOREIGN KEY (payer_id) REFERENCES users (id),
  CONSTRAINT fk_settlements_payee FOREIGN KEY (payee_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_settlements_trip_id ON settlements (trip_id);
CREATE INDEX IF NOT EXISTS idx_settlements_payer_id ON settlements (payer_id);
CREATE INDEX IF NOT EXISTS idx_settlements_payee_id ON settlements (payee_id);
